# Generated by Django 4.1.3 on 2023-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_rides_options_alter_rides_creator_userprofiles_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofiles",
            old_name="rating",
            new_name="avg_rating",
        ),
    ]
