# Generated by Django 4.1.7 on 2023-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_rating_userprofiles_avg_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiles",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
