# Generated by Django 4.1.7 on 2023-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofiles_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="rides",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Ride is open"),
                    ("Closed", "Ride is closed"),
                    ("Confirmed", "Ride is confirmed"),
                ],
                default="Open",
                max_length=10,
            ),
        ),
    ]
