# Generated by Django 4.1.7 on 2023-04-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rides_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rides",
            name="status",
        ),
        migrations.AddField(
            model_name="rides",
            name="type",
            field=models.CharField(
                choices=[("Taxi", "Taxi"), ("Personal Car", "Personal Car")],
                default="Personal Car",
                max_length=15,
            ),
        ),
    ]
