# Generated by Django 4.1.7 on 2023-04-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_type_rides_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiles",
            name="email",
        ),
    ]
