# Generated by Django 4.1.7 on 2023-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_userprofiles_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequests",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
