# Generated by Django 4.1.7 on 2023-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_riderequests_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderequests",
            name="accepted",
        ),
        migrations.AddField(
            model_name="riderequests",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
