# Generated by Django 4.1.7 on 2023-04-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_ratings_comment_ratings_status_rides_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofiles",
            name="avg_rating",
        ),
        migrations.DeleteModel(
            name="Ratings",
        ),
    ]
