# Generated by Django 4.1.7 on 2023-04-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_userprofiles_avg_rating_delete_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofiles",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
