# Generated by Django 4.1.7 on 2023-04-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_userprofiles_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofiles",
            name="profile_pic",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
