# Generated by Django 4.1.7 on 2023-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_userprofiles_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rides",
            name="seats",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="userprofiles",
            name="profile_pic",
            field=models.URLField(
                blank=True,
                default="https://i.pinimg.com/736x/36/df/0a/36df0abbd305ce828abfb78114e2af11.jpg",
                max_length=500,
                null=True,
            ),
        ),
    ]
