# Generated by Django 4.1.7 on 2023-04-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_alter_conversation_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessage",
            name="content",
            field=models.CharField(max_length=1000),
        ),
    ]
